### ISSUE TITLE
[Bug] create-aleo-app/template-extension is outdated - the ManifestV2 is deprecated

### ISSUE THREAD

**Issue by LouisWT** [AleoHQ/aleo#783] opened 2023-10-19 03:23 UTC
## 🚀 Feature

The template-extension example that use ManifestV3.

## Motivation

https://developer.chrome.com/docs/extensions/mv2/
As you can see in Google's doc, manifest v2 has been deprecated, and the Chrome Web Store no longer accepts Manifest V2 extensions. So, developers need a more practical example. (In fact, I'm stuck in how to package @aleohq/sdk to background's service work script in Manifest v3).

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I haven't solve this problem.

**Comment by onetrickwolf** [comment] 2023-10-19 03:25
Thanks for the report but duplicate of https://github.com/AleoHQ/sdk/issues/773

**Closed as not planned by onetrickwolf** 2023-10-19 03:25 UTC

**Comment by onetrickwolf** [comment] 2023-11-07 17:35
@LouisWT we have an updated template now: https://github.com/AleoHQ/sdk/pull/802
