### ISSUE TITLE
[Bug] Unable to cast more than 8 elements into an interface

### ISSUE THREAD

**Issue by ncontinanza** [AleoHQ/aleo#290] opened 2022-07-29 14:48 UTC
## 🐛 Bug Report

I'm trying to cast a set of fields into an interface that represents an array of 784 elements. As far as I could test, this is not possible  for anything greater than 8 elements.

## Steps to Reproduce
For the sake of clarity and legibility, 9 elements will be used instead of 784.

#### Code snippet to reproduce

The following example works as expected when executing the circuit as: `aleo run hello_world 1field 2field 3field 4field 5field 6field 7field 8field`
```
interface array8:
  a0 as field;
  a1 as field;
  a2 as field;
  a3 as field;
  a4 as field;
  a5 as field;
  a6 as field;
  a7 as field;
  
function hello_world:
  input r0 as field.public;
  input r1 as field.public;
  input r2 as field.public;
  input r3 as field.public;
  input r4 as field.public;
  input r5 as field.public;
  input r6 as field.public;
  input r7 as field.public;
  
  cast r0 r1 r2 r3 r4 r5 r6 r7 into r8 as array8;

  output r8 as array8.public;
```
Output: 
```
$ aleo run hello_world 1field 2field 3field 4field 5field 6field 7field 8field

⏳ Compiling 'tests.aleo'...

 • Called universal setup: 11326 ms
 • Called setup: 11306 ms

🚀 Executing 'tests.aleo/hello_world'...

 • Called prover: 1415 ms

➡️  Output

 • {
  a0: 1field,
  a1: 2field,
  a2: 3field,
  a3: 4field,
  a4: 5field,
  a5: 6field,
  a6: 7field,
  a7: 8field
}

✅ Executed 'tests.aleo/hello_world' 
```
The following example results in an error, when trying to do the same as before with one more element:

```
interface array9:
  a0 as field;
  a1 as field;
  a2 as field;
  a3 as field;
  a4 as field;
  a5 as field;
  a6 as field;
  a7 as field;
  a8 as field;
  
function hello_world:
  input r0 as field.public;
  input r1 as field.public;
  input r2 as field.public;
  input r3 as field.public;
  input r4 as field.public;
  input r5 as field.public;
  input r6 as field.public;
  input r7 as field.public;
  input r8 as field.public;
  
  cast r0 r1 r2 r3 r4 r5 r6 r7 r8 into r9 as array9;

  output r9 as array9.public;
```
#### Stack trace & error message

```
$ aleo run hello_world 1field 2field 3field 4field 5field 6field 7field 8field 9field

⚠️  Failed to parse string. Remaining invalid string is: "function hello_world:
  input r0 as field.public;
  input r1 as field.public;
  input r2 as field.public;
  input r3 as field.public;
  input r4 as field.public;
  input r5 as field.public;
  input r6 as field.public;
  input r7 as field.public;
  input r8 as field.public;
  
  cast r0 r1 r2 r3 r4 r5 r6 r7 r8 into r9 as array9;

  output r9 as array9.public;
```

## Expected Behavior

The expected output would have been an array9 interface such as the following:
```
➡️  Output

 • {
  a0: 1field,
  a1: 2field,
  a2: 3field,
  a3: 4field,
  a4: 5field,
  a5: 6field,
  a6: 7field,
  a7: 8field,
  a8: 9field,
}
```
## Your Environment

- Aleo Version: 0.2.0
- Rust Version: 1.62.0
- Computer OS: macOS Monterey 12.4

**Comment by howardwu** [comment] 2022-08-17 08:30
Closing as this is intended behavior.

For those who are inputting more than 8 items, use `interface` to define a custom object (which allows you to input far more than 8 items now). The reason we restrict to 8 items has to do with the Merkle tree/cryptography under the hood.

**Closed by howardwu** 2022-08-17 08:30 UTC
Labels: bug
